---
- name: Bootstrap Arch system
  hosts: localhost
  become: true
  roles:
    - { role: base, tags: ['base'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: grub, tags: ['grub'] }
    - { role: openssh, tags: ['openssh'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: gdm, tags: ['gdm'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: git, tags: ['git'] }
    - { role: nextcloud, tags: ['nextcloud'], when: nextcloud.enabled }
    - { role: terminator, tags: ['terminator'] }
