---
- name: Install Python passlib
  ansible.builtin.package:
    name: python-passlib
    state: present

- name: Create group
  ansible.builtin.group:
    name: "{{ user.group }}"
    gid: "{{ user.gid }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ password | string | password_hash('sha512') }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups: wheel
    append: true
  when: password is defined

- name: Create user socket directory
  ansible.builtin.file:
    path: /run/user/{{ user.uid }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700

- name: Start user systemd instance
  ansible.builtin.systemd:
    name: "user@{{ user.uid }}"
    state: started
  notify: Stop user systemd instance
