---
- name: Install GNOME
  become: true
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - xorg-server-xwayland
    state: present
    use: "{{ aur.tool }}"

- name: Install theme packages
  become: true
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name: "{{ gnome.theme_packages }}"
    state: present
    use: "{{ aur.tool }}"

- name: Configure GNOME settings
  become: true
  become_user: "{{ user.name }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ gnome.settings }}"
