---
- name: Install NetworkManager
  become: true
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name: networkmanager
    state: present

- name: Install NetworkManager extra packages
  become: true
  become_user: "{{ user.name }}"
  kewlfft.aur.aur:
    name: "{{ networkmanager.extra_packages }}"
    state: present

- name: Enable and start NetworkManager
  ansible.builtin.service:
    name: NetworkManager.service
    enabled: true
    state: started
